# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-10 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20180110_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='default location', max_length=120),
        ),
    ]
